version: 1.0.{build}

environment:
  matrix:
    - compiler: msvc_msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
    - compiler: msvc_msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32

before_build:
    - set PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%
    - bash -lc "for i in {1..3}; do update-core && break || sleep 15; done"
    # msys2's plplot does not have the cairo bindings but that should not impact this build
    - bash -lc "for i in {1..3}; do pacman --noconfirm -Su mingw-w64-%MSYS2_ARCH%-{gcc,libtool,gtkmm3,boost} automake autoconf make && break || sleep 15; done"
    # install mm-common
    - bash -lc "wget https://download.gnome.org/sources/mm-common/0.9/mm-common-0.9.10.tar.xz && tar xvfJ mm-common-0.9.10.tar.xz && cd mm-common-0.9.10 && ./configure && make && make install"
    # install PLplot
    - bash -lc "git clone --depth 1 git://git.code.sf.net/p/plplot/plplot && cd plplot && cmake -G \"MSYS Makefiles\" -DENABLE_DYNDRIVERS=OFF -DPLD_wingcc=OFF -DCMAKE_INSTALL_PREFIX=/usr/local . && make && make install"

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - echo %cd%
    - dir
    - bash -lc "cd $APPVEYOR_BUILD_FOLDER && exec 0</dev/null && ACLOCAL_PATH=/usr/local/share/aclocal autoreconf -fi && PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig ./configure && make && make check && make distcheck"
    #- perl -i".bak" -pe "s/^test -n \".DJDIR\"/#$&/" configure
    #- bash -lc "./configure && make && make check && make distcheck"


