var searchData=
[
  ['uimanager',['UIManager',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1UIManager.html',1,'Gtk']]],
  ['unary_5fcompose',['unary_compose',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00080.html',1,'__gnu_cxx']]],
  ['unary_5ffunction',['unary_function',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00948.html',1,'std']]],
  ['unary_5ffunction_3c_20_5f_5fgnu_5fcxx_3a_3athrow_5fvalue_5flimit_2c_20size_5ft_20_3e',['unary_function&lt; __gnu_cxx::throw_value_limit, size_t &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00948.html',1,'std']]],
  ['unary_5ffunction_3c_20_5f_5fgnu_5fcxx_3a_3athrow_5fvalue_5frandom_2c_20size_5ft_20_3e',['unary_function&lt; __gnu_cxx::throw_value_random, size_t &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00948.html',1,'std']]],
  ['unary_5ffunction_3c_20_5foperation_3a_3afirst_5fargument_5ftype_2c_20_5foperation_3a_3aresult_5ftype_20_3e',['unary_function&lt; _Operation::first_argument_type, _Operation::result_type &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00948.html',1,'std']]],
  ['unary_5ffunction_3c_20_5foperation_3a_3asecond_5fargument_5ftype_2c_20_5foperation_3a_3aresult_5ftype_20_3e',['unary_function&lt; _Operation::second_argument_type, _Operation::result_type &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00948.html',1,'std']]],
  ['unary_5ffunction_3c_20_5fpredicate_3a_3aargument_5ftype_2c_20bool_20_3e',['unary_function&lt; _Predicate::argument_type, bool &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00948.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ft1_2c_20_5fres_20_3e',['unary_function&lt; _T1, _Res &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00948.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_20_2a_2c_20_5fret_20_3e',['unary_function&lt; _Tp *, _Ret &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00948.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20_5fret_20_3e',['unary_function&lt; _Tp, _Ret &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00948.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20_5ftp_20_3e',['unary_function&lt; _Tp, _Tp &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00948.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20bool_20_3e',['unary_function&lt; _Tp, bool &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00948.html',1,'std']]],
  ['unary_5ffunction_3c_20const_20_5ftp_20_2a_2c_20_5fret_20_3e',['unary_function&lt; const _Tp *, _Ret &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00948.html',1,'std']]],
  ['unary_5fnegate',['unary_negate',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00949.html',1,'std']]],
  ['unbalanced_5ftag',['unbalanced_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00185.html',1,'__gnu_parallel']]],
  ['underflow_5ferror',['underflow_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00950.html',1,'std']]],
  ['uniform_5fint_5fdistribution',['uniform_int_distribution',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00951.html',1,'std']]],
  ['uniform_5freal_5fdistribution',['uniform_real_distribution',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00953.html',1,'std']]],
  ['unique_5flock',['unique_lock',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00955.html',1,'std']]],
  ['unique_5fptr',['unique_ptr',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00956.html',1,'std']]],
  ['unique_5fptr_3c_20_5ftp_5b_5d_2c_20_5fdp_20_3e',['unique_ptr&lt; _Tp[], _Dp &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00957.html',1,'std']]],
  ['unixconnection',['UnixConnection',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1UnixConnection.html',1,'Gio']]],
  ['unixcredentialsmessage',['UnixCredentialsMessage',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1UnixCredentialsMessage.html',1,'Gio']]],
  ['unixfdlist',['UnixFDList',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1UnixFDList.html',1,'Gio']]],
  ['unixfdmessage',['UnixFDMessage',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1UnixFDMessage.html',1,'Gio']]],
  ['unixinputstream',['UnixInputStream',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1UnixInputStream.html',1,'Gio']]],
  ['unixoutputstream',['UnixOutputStream',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1UnixOutputStream.html',1,'Gio']]],
  ['unixsocketaddress',['UnixSocketAddress',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1UnixSocketAddress.html',1,'Gio']]],
  ['unordered_5fmap',['unordered_map',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00484.html',1,'std::__debug']]],
  ['unordered_5fmap',['unordered_map',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00543.html',1,'std::__profile']]],
  ['unordered_5fmap',['unordered_map',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00958.html',1,'std']]],
  ['unordered_5fmultimap',['unordered_multimap',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00544.html',1,'std::__profile']]],
  ['unordered_5fmultimap',['unordered_multimap',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00959.html',1,'std']]],
  ['unordered_5fmultimap',['unordered_multimap',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00485.html',1,'std::__debug']]],
  ['unordered_5fmultiset',['unordered_multiset',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00486.html',1,'std::__debug']]],
  ['unordered_5fmultiset',['unordered_multiset',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00545.html',1,'std::__profile']]],
  ['unordered_5fmultiset',['unordered_multiset',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00960.html',1,'std']]],
  ['unordered_5fset',['unordered_set',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00546.html',1,'std::__profile']]],
  ['unordered_5fset',['unordered_set',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00487.html',1,'std::__debug']]],
  ['unordered_5fset',['unordered_set',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00961.html',1,'std']]],
  ['unwrap_5flambda_5ftype',['unwrap_lambda_type',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1unwrap__lambda__type.html',1,'sigc']]],
  ['unwrap_5flambda_5ftype_3c_20lambda_3c_20t_5ftype_20_3e_20_3e',['unwrap_lambda_type&lt; lambda&lt; T_type &gt; &gt;',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1unwrap__lambda__type_3_01lambda_3_01T__type_01_4_01_4.html',1,'sigc']]],
  ['unwrap_5freference',['unwrap_reference',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1unwrap__reference.html',1,'sigc']]],
  ['unwrap_5freference_3c_20const_5freference_5fwrapper_3c_20t_5ftype_20_3e_20_3e',['unwrap_reference&lt; const_reference_wrapper&lt; T_type &gt; &gt;',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1unwrap__reference_3_01const__reference__wrapper_3_01T__type_01_4_01_4.html',1,'sigc']]],
  ['unwrap_5freference_3c_20reference_5fwrapper_3c_20t_5ftype_20_3e_20_3e',['unwrap_reference&lt; reference_wrapper&lt; T_type &gt; &gt;',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1unwrap__reference_3_01reference__wrapper_3_01T__type_01_4_01_4.html',1,'sigc']]],
  ['userfontface',['UserFontFace',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1UserFontFace.html',1,'Cairo']]],
  ['uses_5fallocator',['uses_allocator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00962.html',1,'std']]],
  ['uses_5fallocator_3c_20tuple_3c_20_5ftypes_2e_2e_2e_20_3e_2c_20_5falloc_20_3e',['uses_allocator&lt; tuple&lt; _Types... &gt;, _Alloc &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00963.html',1,'std']]],
  ['ustring',['ustring',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1ustring.html',1,'Glib']]],
  ['ustring_5fiterator',['ustring_Iterator',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1ustring__Iterator.html',1,'Glib']]]
];
