var searchData=
[
  ['sample_5fprobe_5ffn',['sample_probe_fn',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10704.html',1,'__gnu_pbds']]],
  ['sample_5frange_5fhashing',['sample_range_hashing',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10708.html',1,'__gnu_pbds']]],
  ['sample_5franged_5fhash_5ffn',['sample_ranged_hash_fn',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10712.html',1,'__gnu_pbds']]],
  ['sample_5franged_5fprobe_5ffn',['sample_ranged_probe_fn',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10716.html',1,'__gnu_pbds']]],
  ['sample_5fresize_5fpolicy',['sample_resize_policy',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10928.html',1,'__gnu_pbds']]],
  ['sample_5fresize_5ftrigger',['sample_resize_trigger',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10932.html',1,'__gnu_pbds']]],
  ['sample_5fsize_5fpolicy',['sample_size_policy',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10936.html',1,'__gnu_pbds']]],
  ['sample_5ftree_5fnode_5fupdate',['sample_tree_node_update',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10980.html',1,'__gnu_pbds']]],
  ['sample_5ftrie_5faccess_5ftraits',['sample_trie_access_traits',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a11000.html',1,'__gnu_pbds']]],
  ['sample_5ftrie_5fnode_5fupdate',['sample_trie_node_update',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a11004.html',1,'__gnu_pbds']]],
  ['sample_5fupdate_5fpolicy',['sample_update_policy',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10780.html',1,'__gnu_pbds']]],
  ['sampling_5ftag',['sampling_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08664.html',1,'__gnu_parallel']]],
  ['scale',['Scale',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Scale.html',1,'Gtk']]],
  ['scalebutton',['ScaleButton',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1ScaleButton.html',1,'Gtk']]],
  ['scaledfont',['ScaledFont',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1ScaledFont.html',1,'Cairo']]],
  ['scoped_5fallocator_5fadaptor',['scoped_allocator_adaptor',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02864.html',1,'std']]],
  ['scoped_5fallocator_5fadaptor_3c_20_5finnerhead_2c_20_5finnertail_2e_2e_2e_20_3e',['scoped_allocator_adaptor&lt; _InnerHead, _InnerTail... &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02864.html',1,'']]],
  ['screen',['Screen',['http://library.gnome.org/devel/gtkmm/unstable/classGdk_1_1Screen.html',1,'Gdk']]],
  ['scrollable',['Scrollable',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Scrollable.html',1,'Gtk']]],
  ['scrollbar',['Scrollbar',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Scrollbar.html',1,'Gtk']]],
  ['scrolledwindow',['ScrolledWindow',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1ScrolledWindow.html',1,'Gtk']]],
  ['searchbar',['SearchBar',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1SearchBar.html',1,'Gtk']]],
  ['searchentry',['SearchEntry',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1SearchEntry.html',1,'Gtk']]],
  ['seat',['Seat',['http://library.gnome.org/devel/gtkmm/unstable/classGdk_1_1Seat.html',1,'Gdk']]],
  ['seed_5fseq',['seed_seq',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05584.html',1,'std']]],
  ['seekable',['Seekable',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1Seekable.html',1,'Gio']]],
  ['select1st',['select1st',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08096.html',1,'__gnu_cxx']]],
  ['select2nd',['select2nd',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08100.html',1,'__gnu_cxx']]],
  ['selection',['Selection',['http://library.gnome.org/devel/atkmm/unstable/classAtk_1_1Selection.html',1,'Atk']]],
  ['selectiondata',['SelectionData',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1SelectionData.html',1,'Gtk']]],
  ['sentry',['sentry',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02756.html',1,'std::basic_ostream&lt; _CharT, _Traits &gt;::sentry'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02608.html',1,'std::basic_istream&lt; _CharT, _Traits &gt;::sentry']]],
  ['separator',['Separator',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Separator.html',1,'Gtk']]],
  ['separatormenuitem',['SeparatorMenuItem',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1SeparatorMenuItem.html',1,'Gtk']]],
  ['separatortoolitem',['SeparatorToolItem',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1SeparatorToolItem.html',1,'Gtk']]],
  ['sequence',['Sequence',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Sequence.html',1,'Glib']]],
  ['sequence_5ftag',['sequence_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10132.html',1,'__gnu_pbds']]],
  ['sequential_5ftag',['sequential_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08628.html',1,'__gnu_parallel']]],
  ['server',['Server',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1DBus_1_1Server.html',1,'Gio::DBus']]],
  ['set',['set',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06732.html',1,'std::set&lt; _Key, _Compare, _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07728.html',1,'std::__debug::set&lt; _Key, _Compare, _Allocator &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07864.html',1,'std::__profile::set&lt; _Key, _Compare, _Allocator &gt;']]],
  ['settings',['Settings',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1Settings.html',1,'Gio::Settings'],['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Settings.html',1,'Gtk::Settings']]],
  ['settingsschema',['SettingsSchema',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SettingsSchema.html',1,'Gio']]],
  ['settingsschemakey',['SettingsSchemaKey',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SettingsSchemaKey.html',1,'Gio']]],
  ['settingsschemasource',['SettingsSchemaSource',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SettingsSchemaSource.html',1,'Gio']]],
  ['shared_5ffuture',['shared_future',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02352.html',1,'std']]],
  ['shared_5ffuture_3c_20_5fres_20_26_3e',['shared_future&lt; _Res &amp;&gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02468.html',1,'std']]],
  ['shared_5ffuture_3c_20void_20_3e',['shared_future&lt; void &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02472.html',1,'std']]],
  ['shared_5flock',['shared_lock',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02892.html',1,'std']]],
  ['shared_5fptr',['shared_ptr',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'std']]],
  ['shared_5fptr_3c_20_5fdir_20_3e',['shared_ptr&lt; _Dir &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20_5fdir_5fstack_20_3e',['shared_ptr&lt; _Dir_stack &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20_5fregext_20_3e',['shared_ptr&lt; _RegexT &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20_5fstate_20_3e',['shared_ptr&lt; _State &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20_5fstate_5fbase_20_3e',['shared_ptr&lt; _State_base &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20_5fstate_5ftype_20_3e',['shared_ptr&lt; _State_type &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20const_20_5f_5fdetail_3a_3a_5fnfa_3c_20_5frx_5ftraits_20_3e_20_3e',['shared_ptr&lt; const __detail::_NFA&lt; _Rx_traits &gt; &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5fptr_3c_20std_3a_3amutex_20_3e',['shared_ptr&lt; std::mutex &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05936.html',1,'']]],
  ['shared_5ftimed_5fmutex',['shared_timed_mutex',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02888.html',1,'std']]],
  ['shellerror',['ShellError',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1ShellError.html',1,'Glib']]],
  ['shortcutlabel',['ShortcutLabel',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1ShortcutLabel.html',1,'Gtk']]],
  ['shortcutsgroup',['ShortcutsGroup',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1ShortcutsGroup.html',1,'Gtk']]],
  ['shortcutssection',['ShortcutsSection',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1ShortcutsSection.html',1,'Gtk']]],
  ['shortcutsshortcut',['ShortcutsShortcut',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1ShortcutsShortcut.html',1,'Gtk']]],
  ['shortcutswindow',['ShortcutsWindow',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1ShortcutsWindow.html',1,'Gtk']]],
  ['shuffle_5forder_5fengine',['shuffle_order_engine',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05420.html',1,'std']]],
  ['signal',['signal',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal.html',1,'sigc']]],
  ['signal0',['signal0',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal0.html',1,'sigc']]],
  ['signal0_3c_20t_5freturn_2c_20nil_20_3e',['signal0&lt; T_return, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal0.html',1,'']]],
  ['signal1',['signal1',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal1.html',1,'sigc']]],
  ['signal1_3c_20t_5freturn_2c_20t_5farg1_2c_20nil_20_3e',['signal1&lt; T_return, T_arg1, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal1.html',1,'']]],
  ['signal2',['signal2',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal2.html',1,'sigc']]],
  ['signal2_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20nil_20_3e',['signal2&lt; T_return, T_arg1, T_arg2, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal2.html',1,'']]],
  ['signal3',['signal3',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal3.html',1,'sigc']]],
  ['signal3_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20nil_20_3e',['signal3&lt; T_return, T_arg1, T_arg2, T_arg3, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal3.html',1,'']]],
  ['signal4',['signal4',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal4.html',1,'sigc']]],
  ['signal4_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20nil_20_3e',['signal4&lt; T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal4.html',1,'']]],
  ['signal5',['signal5',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal5.html',1,'sigc']]],
  ['signal5_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20t_5farg5_2c_20nil_20_3e',['signal5&lt; T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal5.html',1,'']]],
  ['signal6',['signal6',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal6.html',1,'sigc']]],
  ['signal6_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20t_5farg5_2c_20t_5farg6_2c_20nil_20_3e',['signal6&lt; T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal6.html',1,'']]],
  ['signal7',['signal7',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal7.html',1,'sigc']]],
  ['signal7_3c_20std_3a_3avector_3c_20double_20_3e_2c_20double_2c_20double_2c_20double_2c_20double_2c_20t_5farg5_2c_20t_5farg6_2c_20t_5farg7_2c_20nil_20_3e',['signal7&lt; std::vector&lt; double &gt;, double, double, double, double, T_arg5, T_arg6, T_arg7, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal7.html',1,'sigc']]],
  ['signal7_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20t_5farg5_2c_20t_5farg6_2c_20t_5farg7_2c_20nil_20_3e',['signal7&lt; T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal7.html',1,'']]],
  ['signal7_3c_20void_2c_20double_2c_20double_2c_20double_2c_20double_2c_20t_5farg5_2c_20t_5farg6_2c_20t_5farg7_2c_20nil_20_3e',['signal7&lt; void, double, double, double, double, T_arg5, T_arg6, T_arg7, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal7.html',1,'sigc']]],
  ['signal7_3c_20void_2c_20double_2c_20double_2c_20gdkscrolldirection_2c_20t_5farg4_2c_20t_5farg5_2c_20t_5farg6_2c_20t_5farg7_2c_20nil_20_3e',['signal7&lt; void, double, double, GdkScrollDirection, T_arg4, T_arg5, T_arg6, T_arg7, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal7.html',1,'sigc']]],
  ['signal7_3c_20void_2c_20double_2c_20double_2c_20t_5farg3_2c_20t_5farg4_2c_20t_5farg5_2c_20t_5farg6_2c_20t_5farg7_2c_20nil_20_3e',['signal7&lt; void, double, double, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal7.html',1,'sigc']]],
  ['signal7_3c_20void_2c_20gtk_3a_3aplplot_3a_3aplotdata_20_2a_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20t_5farg5_2c_20t_5farg6_2c_20t_5farg7_2c_20nil_20_3e',['signal7&lt; void, Gtk::PLplot::PlotData *, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal7.html',1,'sigc']]],
  ['signal7_3c_20void_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20t_5farg5_2c_20t_5farg6_2c_20t_5farg7_2c_20nil_20_3e',['signal7&lt; void, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal7.html',1,'sigc']]],
  ['signal_3c_20std_3a_3avector_3c_20double_20_3e_2c_20double_2c_20double_2c_20double_2c_20double_20_3e',['signal&lt; std::vector&lt; double &gt;, double, double, double, double &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_28_29_3e',['signal&lt; T_return()&gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_07_08_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_28t_5farg1_29_3e',['signal&lt; T_return(T_arg1)&gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_07T__arg1_08_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_28t_5farg1_2c_20t_5farg2_29_3e',['signal&lt; T_return(T_arg1, T_arg2)&gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_08_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_28t_5farg1_2c_20t_5farg2_2c_20t_5farg3_29_3e',['signal&lt; T_return(T_arg1, T_arg2, T_arg3)&gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_00_01T__arg3_08_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_28t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_29_3e',['signal&lt; T_return(T_arg1, T_arg2, T_arg3, T_arg4)&gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_00_01T__arg3_00_01T__arg4_08_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_28t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20t_5farg5_29_3e',['signal&lt; T_return(T_arg1, T_arg2, T_arg3, T_arg4, T_arg5)&gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_00_01T__arg3_00_01T__arg4_00_01T__arg5_08_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_28t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20t_5farg5_2c_20t_5farg6_29_3e',['signal&lt; T_return(T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6)&gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_00_01T__arg3_00_01T__arg4_00_01T__arg5_00_01T__arg6_08_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_28t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20t_5farg5_2c_20t_5farg6_2c_20t_5farg7_29_3e',['signal&lt; T_return(T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, T_arg7)&gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_00_01T__arg3_00_01T__arg4_00_01T__arg5_00_01T__arg6_00_01T__arg7_08_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_2c_20nil_2c_20nil_2c_20nil_2c_20nil_2c_20nil_2c_20nil_2c_20nil_20_3e',['signal&lt; T_return, nil, nil, nil, nil, nil, nil, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_00_01nil_00_01nil_00_01nil_00_01nil_00_01nil_00_01nil_00_01nil_01_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_2c_20t_5farg1_2c_20nil_2c_20nil_2c_20nil_2c_20nil_2c_20nil_2c_20nil_20_3e',['signal&lt; T_return, T_arg1, nil, nil, nil, nil, nil, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_00_01T__arg1_00_01nil_00_01nil_00_01nil_00_01nil_00_01nil_00_01nil_01_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20nil_2c_20nil_2c_20nil_2c_20nil_2c_20nil_20_3e',['signal&lt; T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_00_01T__arg1_00_01T__arg2_00_01nil_00_01nil_00_01nil_00_01nil_00_01nil_01_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20nil_2c_20nil_2c_20nil_2c_20nil_20_3e',['signal&lt; T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_00_01T__arg1_00_01T__arg2_00_01T__arg3_00_01nil_00_01nil_00_01nil_00_01nil_01_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20nil_2c_20nil_2c_20nil_20_3e',['signal&lt; T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_00_01T__arg1_00_01T__arg2_00_01T__arg3_00_01T__arg4_00_01nil_00_01nil_00_01nil_01_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20t_5farg5_2c_20nil_2c_20nil_20_3e',['signal&lt; T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_00_01T__arg1_00_01T__arg2_00_01T__arg3_00_01T__arg4_00_01T__arg5_00_01nil_00_01nil_01_4.html',1,'sigc']]],
  ['signal_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20t_5farg5_2c_20t_5farg6_2c_20nil_20_3e',['signal&lt; T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal_3_01T__return_00_01T__arg1_00_01T__arg2_00_01T__arg3_00_01T__arg4_00_01T__arg5_00_01T__arg6_00_01nil_01_4.html',1,'sigc']]],
  ['signal_3c_20void_20_3e',['signal&lt; void &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal.html',1,'sigc']]],
  ['signal_3c_20void_2c_20double_2c_20double_20_3e',['signal&lt; void, double, double &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal.html',1,'sigc']]],
  ['signal_3c_20void_2c_20double_2c_20double_2c_20double_2c_20double_20_3e',['signal&lt; void, double, double, double, double &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal.html',1,'sigc']]],
  ['signal_3c_20void_2c_20double_2c_20double_2c_20gdkscrolldirection_20_3e',['signal&lt; void, double, double, GdkScrollDirection &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal.html',1,'sigc']]],
  ['signal_3c_20void_2c_20gtk_3a_3aplplot_3a_3aplotdata_20_2a_3e',['signal&lt; void, Gtk::PLplot::PlotData *&gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1signal.html',1,'sigc']]],
  ['signal_5fbase',['signal_base',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1signal__base.html',1,'sigc']]],
  ['signalchildwatch',['SignalChildWatch',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1SignalChildWatch.html',1,'Glib']]],
  ['signalidle',['SignalIdle',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1SignalIdle.html',1,'Glib']]],
  ['signalinfo',['SignalInfo',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1DBus_1_1SignalInfo.html',1,'Gio::DBus']]],
  ['signalio',['SignalIO',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1SignalIO.html',1,'Glib']]],
  ['signalproxy',['SignalProxy',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1SignalProxy.html',1,'Glib']]],
  ['signalproxybase',['SignalProxyBase',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1SignalProxyBase.html',1,'Glib']]],
  ['signalproxychildproperty',['SignalProxyChildProperty',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1SignalProxyChildProperty.html',1,'Gtk']]],
  ['signalproxydetailed',['SignalProxyDetailed',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1SignalProxyDetailed.html',1,'Glib']]],
  ['signalproxydetailedanytype',['SignalProxyDetailedAnyType',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1SignalProxyDetailedAnyType.html',1,'Glib']]],
  ['signalproxynormal',['SignalProxyNormal',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1SignalProxyNormal.html',1,'Glib']]],
  ['signalproxyproperty',['SignalProxyProperty',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1SignalProxyProperty.html',1,'Glib']]],
  ['signalsocket',['SignalSocket',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SignalSocket.html',1,'Gio']]],
  ['signaltimeout',['SignalTimeout',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1SignalTimeout.html',1,'Glib']]],
  ['simpleaction',['SimpleAction',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SimpleAction.html',1,'Gio']]],
  ['simpleactiongroup',['SimpleActionGroup',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SimpleActionGroup.html',1,'Gio']]],
  ['simpleiostream',['SimpleIOStream',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SimpleIOStream.html',1,'Gio']]],
  ['simplepermission',['SimplePermission',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SimplePermission.html',1,'Gio']]],
  ['sizegroup',['SizeGroup',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1SizeGroup.html',1,'Gtk']]],
  ['slice',['slice',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06152.html',1,'std']]],
  ['slice_5farray',['slice_array',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03752.html',1,'std']]],
  ['slist',['slist',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08260.html',1,'__gnu_cxx']]],
  ['slisthandle',['SListHandle',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1SListHandle.html',1,'Glib']]],
  ['slisthandleiterator',['SListHandleIterator',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Container__Helpers_1_1SListHandleIterator.html',1,'Glib::Container_Helpers']]],
  ['slisthandler',['SListHandler',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1SListHandler.html',1,'Glib']]],
  ['slistiterator',['SListIterator',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Container__Helpers_1_1SListIterator.html',1,'Glib::Container_Helpers']]],
  ['slot',['slot',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot.html',1,'sigc']]],
  ['slot0',['slot0',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot0.html',1,'sigc']]],
  ['slot1',['slot1',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot1.html',1,'sigc']]],
  ['slot2',['slot2',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot2.html',1,'sigc']]],
  ['slot3',['slot3',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot3.html',1,'sigc']]],
  ['slot4',['slot4',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot4.html',1,'sigc']]],
  ['slot5',['slot5',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot5.html',1,'sigc']]],
  ['slot6',['slot6',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot6.html',1,'sigc']]],
  ['slot7',['slot7',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot7.html',1,'sigc']]],
  ['slot_3c_20t_5freturn_28t_5farg_2e_2e_2e_29_3e',['slot&lt; T_return(T_arg...)&gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot_3_01T__return_07T__arg_8_8_8_08_4.html',1,'sigc']]],
  ['slot_3c_20t_5freturn_2c_20nil_2c_20nil_2c_20nil_2c_20nil_2c_20nil_2c_20nil_2c_20nil_20_3e',['slot&lt; T_return, nil, nil, nil, nil, nil, nil, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot_3_01T__return_00_01nil_00_01nil_00_01nil_00_01nil_00_01nil_00_01nil_00_01nil_01_4.html',1,'sigc']]],
  ['slot_3c_20t_5freturn_2c_20t_5farg1_2c_20nil_2c_20nil_2c_20nil_2c_20nil_2c_20nil_2c_20nil_20_3e',['slot&lt; T_return, T_arg1, nil, nil, nil, nil, nil, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot_3_01T__return_00_01T__arg1_00_01nil_00_01nil_00_01nil_00_01nil_00_01nil_00_01nil_01_4.html',1,'sigc']]],
  ['slot_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20nil_2c_20nil_2c_20nil_2c_20nil_2c_20nil_20_3e',['slot&lt; T_return, T_arg1, T_arg2, nil, nil, nil, nil, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot_3_01T__return_00_01T__arg1_00_01T__arg2_00_01nil_00_01nil_00_01nil_00_01nil_00_01nil_01_4.html',1,'sigc']]],
  ['slot_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20nil_2c_20nil_2c_20nil_2c_20nil_20_3e',['slot&lt; T_return, T_arg1, T_arg2, T_arg3, nil, nil, nil, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot_3_01T__return_00_01T__arg1_00_01T__arg2_00_01T__arg3_00_01nil_00_01nil_00_01nil_00_01nil_01_4.html',1,'sigc']]],
  ['slot_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20nil_2c_20nil_2c_20nil_20_3e',['slot&lt; T_return, T_arg1, T_arg2, T_arg3, T_arg4, nil, nil, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot_3_01T__return_00_01T__arg1_00_01T__arg2_00_01T__arg3_00_01T__arg4_00_01nil_00_01nil_00_01nil_01_4.html',1,'sigc']]],
  ['slot_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20t_5farg5_2c_20nil_2c_20nil_20_3e',['slot&lt; T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, nil, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot_3_01T__return_00_01T__arg1_00_01T__arg2_00_01T__arg3_00_01T__arg4_00_01T__arg5_00_01nil_00_01nil_01_4.html',1,'sigc']]],
  ['slot_3c_20t_5freturn_2c_20t_5farg1_2c_20t_5farg2_2c_20t_5farg3_2c_20t_5farg4_2c_20t_5farg5_2c_20t_5farg6_2c_20nil_20_3e',['slot&lt; T_return, T_arg1, T_arg2, T_arg3, T_arg4, T_arg5, T_arg6, nil &gt;',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot_3_01T__return_00_01T__arg1_00_01T__arg2_00_01T__arg3_00_01T__arg4_00_01T__arg5_00_01T__arg6_00_01nil_01_4.html',1,'sigc']]],
  ['slot_5fbase',['slot_base',['http://library.gnome.org/devel/libsigc++/unstable/classsigc_1_1slot__base.html',1,'sigc']]],
  ['slot_5fconst_5fiterator',['slot_const_iterator',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1slot__const__iterator.html',1,'sigc']]],
  ['slot_5fiterator',['slot_iterator',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1slot__iterator.html',1,'sigc']]],
  ['slot_5flist',['slot_list',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1slot__list.html',1,'sigc']]],
  ['socket',['Socket',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Socket.html',1,'Gtk::Socket'],['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1Socket.html',1,'Gio::Socket']]],
  ['socketaddress',['SocketAddress',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SocketAddress.html',1,'Gio']]],
  ['socketaddressenumerator',['SocketAddressEnumerator',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SocketAddressEnumerator.html',1,'Gio']]],
  ['socketclient',['SocketClient',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SocketClient.html',1,'Gio']]],
  ['socketconnectable',['SocketConnectable',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SocketConnectable.html',1,'Gio']]],
  ['socketconnection',['SocketConnection',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SocketConnection.html',1,'Gio']]],
  ['socketcontrolmessage',['SocketControlMessage',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SocketControlMessage.html',1,'Gio']]],
  ['socketlistener',['SocketListener',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SocketListener.html',1,'Gio']]],
  ['socketservice',['SocketService',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SocketService.html',1,'Gio']]],
  ['socketsource',['SocketSource',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SocketSource.html',1,'Gio']]],
  ['solidpattern',['SolidPattern',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1SolidPattern.html',1,'Cairo']]],
  ['source',['Source',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Source.html',1,'Glib']]],
  ['spawnerror',['SpawnError',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1SpawnError.html',1,'Glib']]],
  ['spinbutton',['SpinButton',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1SpinButton.html',1,'Gtk']]],
  ['spinner',['Spinner',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Spinner.html',1,'Gtk']]],
  ['splay_5ftree_5fmap',['splay_tree_map',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10948.html',1,'__gnu_pbds::detail']]],
  ['splay_5ftree_5fnode_5f',['splay_tree_node_',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10940.html',1,'__gnu_pbds::detail']]],
  ['splay_5ftree_5ftag',['splay_tree_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10168.html',1,'__gnu_pbds']]],
  ['srvtarget',['SrvTarget',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1SrvTarget.html',1,'Gio']]],
  ['stack',['stack',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06780.html',1,'std::stack&lt; _Tp, _Sequence &gt;'],['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Stack.html',1,'Gtk::Stack']]],
  ['stack_3c_20_5fstateseqt_20_3e',['stack&lt; _StateSeqT &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06780.html',1,'']]],
  ['stacksidebar',['StackSidebar',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1StackSidebar.html',1,'Gtk']]],
  ['stackswitcher',['StackSwitcher',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1StackSwitcher.html',1,'Gtk']]],
  ['stateset',['StateSet',['http://library.gnome.org/devel/atkmm/unstable/classAtk_1_1StateSet.html',1,'Atk']]],
  ['staticmutex',['StaticMutex',['http://library.gnome.org/devel/glibmm/unstable/structGlib_1_1StaticMutex.html',1,'Glib']]],
  ['staticprivate',['StaticPrivate',['http://library.gnome.org/devel/glibmm/unstable/structGlib_1_1StaticPrivate.html',1,'Glib']]],
  ['staticrecmutex',['StaticRecMutex',['http://library.gnome.org/devel/glibmm/unstable/structGlib_1_1StaticRecMutex.html',1,'Glib']]],
  ['staticrwlock',['StaticRWLock',['http://library.gnome.org/devel/glibmm/unstable/structGlib_1_1StaticRWLock.html',1,'Glib']]],
  ['statusbar',['Statusbar',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Statusbar.html',1,'Gtk']]],
  ['statusicon',['StatusIcon',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1StatusIcon.html',1,'Gtk']]],
  ['stdio_5ffilebuf',['stdio_filebuf',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09588.html',1,'__gnu_cxx']]],
  ['stdio_5fsync_5ffilebuf',['stdio_sync_filebuf',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09592.html',1,'__gnu_cxx']]],
  ['steady_5fclock',['steady_clock',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01916.html',1,'std::chrono::_V2']]],
  ['stockid',['StockID',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1StockID.html',1,'Gtk']]],
  ['stockitem',['StockItem',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1StockItem.html',1,'Gtk']]],
  ['stored_5fdata',['stored_data',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10452.html',1,'__gnu_pbds::detail']]],
  ['stored_5fdata_3c_20_5ftv_2c_20null_5ftype_20_3e',['stored_data&lt; _Tv, null_type &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10456.html',1,'__gnu_pbds::detail']]],
  ['stored_5fhash',['stored_hash',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10448.html',1,'__gnu_pbds::detail']]],
  ['stored_5fvalue',['stored_value',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10444.html',1,'__gnu_pbds::detail']]],
  ['streamablecontent',['StreamableContent',['http://library.gnome.org/devel/atkmm/unstable/classAtk_1_1StreamableContent.html',1,'Atk']]],
  ['streamiochannel',['StreamIOChannel',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1StreamIOChannel.html',1,'Glib']]],
  ['string_5ftag',['string_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10136.html',1,'__gnu_pbds']]],
  ['student_5ft_5fdistribution',['student_t_distribution',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05488.html',1,'std']]],
  ['stylecontext',['StyleContext',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1StyleContext.html',1,'Gtk']]],
  ['styleproperty',['StyleProperty',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1StyleProperty.html',1,'Gtk']]],
  ['stylepropertybase',['StylePropertyBase',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1StylePropertyBase.html',1,'Gtk']]],
  ['styleprovider',['StyleProvider',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1StyleProvider.html',1,'Gtk']]],
  ['sub_5fmatch',['sub_match',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05800.html',1,'std']]],
  ['sub_5fmatch_3c_20_5fbi_5fiter_20_3e',['sub_match&lt; _Bi_iter &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05800.html',1,'']]],
  ['subtract_5fwith_5fcarry_5fengine',['subtract_with_carry_engine',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05408.html',1,'std']]],
  ['subtractive_5frng',['subtractive_rng',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08144.html',1,'__gnu_cxx']]],
  ['subtreevtable',['SubtreeVTable',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1DBus_1_1SubtreeVTable.html',1,'Gio::DBus']]],
  ['surface',['Surface',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1Surface.html',1,'Cairo']]],
  ['surfacepattern',['SurfacePattern',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1SurfacePattern.html',1,'Cairo']]],
  ['svgsurface',['SvgSurface',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1SvgSurface.html',1,'Cairo']]],
  ['switch',['Switch',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Switch.html',1,'Gtk']]],
  ['synth_5faccess_5ftraits',['synth_access_traits',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10876.html',1,'__gnu_pbds::detail']]],
  ['system_5fclock',['system_clock',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01912.html',1,'std::chrono::_V2']]],
  ['system_5ferror',['system_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02964.html',1,'std']]]
];
