var searchData=
[
  ['radialgradient',['RadialGradient',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1RadialGradient.html',1,'Cairo']]],
  ['radioaction',['RadioAction',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RadioAction.html',1,'Gtk']]],
  ['radiobutton',['RadioButton',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RadioButton.html',1,'Gtk']]],
  ['radiobuttongroup',['RadioButtonGroup',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RadioButtonGroup.html',1,'Gtk']]],
  ['radiomenuitem',['RadioMenuItem',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RadioMenuItem.html',1,'Gtk']]],
  ['radiotoolbutton',['RadioToolButton',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RadioToolButton.html',1,'Gtk']]],
  ['rand',['Rand',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Rand.html',1,'Glib']]],
  ['random_5faccess_5fiterator_5ftag',['random_access_iterator_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06668.html',1,'std']]],
  ['random_5fcondition',['random_condition',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09628.html',1,'__gnu_cxx']]],
  ['random_5fdevice',['random_device',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05424.html',1,'std']]],
  ['range',['Range',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Range.html',1,'Gtk::Range'],['http://library.gnome.org/devel/atkmm/unstable/classAtk_1_1Range.html',1,'Atk::Range']]],
  ['range_5ferror',['range_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02924.html',1,'std']]],
  ['range_5finvalidation_5fguarantee',['range_invalidation_guarantee',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10124.html',1,'__gnu_pbds']]],
  ['ranged_5fhash_5ffn',['ranged_hash_fn',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10668.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fhash_5ffn_3c_20key_2c_20hash_5ffn_2c_20_5falloc_2c_20comb_5fhash_5ffn_2c_20false_20_3e',['ranged_hash_fn&lt; Key, Hash_Fn, _Alloc, Comb_Hash_Fn, false &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10672.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fhash_5ffn_3c_20key_2c_20hash_5ffn_2c_20_5falloc_2c_20comb_5fhash_5ffn_2c_20true_20_3e',['ranged_hash_fn&lt; Key, Hash_Fn, _Alloc, Comb_Hash_Fn, true &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10676.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fhash_5ffn_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20comb_5fhash_5ffn_2c_20false_20_3e',['ranged_hash_fn&lt; Key, null_type, _Alloc, Comb_Hash_Fn, false &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10680.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fhash_5ffn_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20comb_5fhash_5ffn_2c_20true_20_3e',['ranged_hash_fn&lt; Key, null_type, _Alloc, Comb_Hash_Fn, true &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10684.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fprobe_5ffn',['ranged_probe_fn',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10688.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fprobe_5ffn_3c_20key_2c_20hash_5ffn_2c_20_5falloc_2c_20comb_5fprobe_5ffn_2c_20probe_5ffn_2c_20false_20_3e',['ranged_probe_fn&lt; Key, Hash_Fn, _Alloc, Comb_Probe_Fn, Probe_Fn, false &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10692.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fprobe_5ffn_3c_20key_2c_20hash_5ffn_2c_20_5falloc_2c_20comb_5fprobe_5ffn_2c_20probe_5ffn_2c_20true_20_3e',['ranged_probe_fn&lt; Key, Hash_Fn, _Alloc, Comb_Probe_Fn, Probe_Fn, true &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10696.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fprobe_5ffn_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20comb_5fprobe_5ffn_2c_20null_5ftype_2c_20false_20_3e',['ranged_probe_fn&lt; Key, null_type, _Alloc, Comb_Probe_Fn, null_type, false &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10700.html',1,'__gnu_pbds::detail']]],
  ['ratio',['ratio',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02828.html',1,'std']]],
  ['ratio_5fequal',['ratio_equal',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02840.html',1,'std']]],
  ['ratio_5fnot_5fequal',['ratio_not_equal',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02844.html',1,'std']]],
  ['raw_5fstorage_5fiterator',['raw_storage_iterator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06776.html',1,'std']]],
  ['rb_5ftree',['rb_tree',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08152.html',1,'__gnu_cxx']]],
  ['rb_5ftree_5fmap',['rb_tree_map',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10896.html',1,'__gnu_pbds::detail']]],
  ['rb_5ftree_5fnode_5f',['rb_tree_node_',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10888.html',1,'__gnu_pbds::detail']]],
  ['rb_5ftree_5ftag',['rb_tree_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10164.html',1,'__gnu_pbds']]],
  ['rc',['rc',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10908.html',1,'__gnu_pbds::detail']]],
  ['rc_3c_20typename_20binomial_5fheap_5fbase_3c_20value_5ftype_2c_20cmp_5ffn_2c_20_5falloc_20_3e_3a_3anode_2c_20_5falloc_20_3e',['rc&lt; typename binomial_heap_base&lt; Value_Type, Cmp_Fn, _Alloc &gt;::node, _Alloc &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10908.html',1,'']]],
  ['rc_5fbinomial_5fheap',['rc_binomial_heap',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10912.html',1,'__gnu_pbds::detail']]],
  ['rc_5fbinomial_5fheap_5ftag',['rc_binomial_heap_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10200.html',1,'__gnu_pbds']]],
  ['readerlock',['ReaderLock',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1RWLock_1_1ReaderLock.html',1,'Glib::RWLock::ReaderLock'],['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Threads_1_1RWLock_1_1ReaderLock.html',1,'Glib::Threads::RWLock::ReaderLock']]],
  ['recentaction',['RecentAction',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentAction.html',1,'Gtk']]],
  ['recentchooser',['RecentChooser',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentChooser.html',1,'Gtk']]],
  ['recentchooserdialog',['RecentChooserDialog',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentChooserDialog.html',1,'Gtk']]],
  ['recentchoosererror',['RecentChooserError',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentChooserError.html',1,'Gtk']]],
  ['recentchoosermenu',['RecentChooserMenu',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentChooserMenu.html',1,'Gtk']]],
  ['recentchooserwidget',['RecentChooserWidget',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentChooserWidget.html',1,'Gtk']]],
  ['recentfilter',['RecentFilter',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentFilter.html',1,'Gtk']]],
  ['recentinfo',['RecentInfo',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentInfo.html',1,'Gtk']]],
  ['recentmanager',['RecentManager',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentManager.html',1,'Gtk']]],
  ['recentmanagererror',['RecentManagerError',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentManagerError.html',1,'Gtk']]],
  ['recmutex',['RecMutex',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Threads_1_1RecMutex.html',1,'Glib::Threads::RecMutex'],['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1RecMutex.html',1,'Glib::RecMutex']]],
  ['rectangle',['Rectangle',['http://library.gnome.org/devel/pangomm/unstable/classPango_1_1Rectangle.html',1,'Pango::Rectangle'],['http://library.gnome.org/devel/gtkmm/unstable/classGdk_1_1Rectangle.html',1,'Gdk::Rectangle']]],
  ['recursive_5finit_5ferror',['recursive_init_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01648.html',1,'__gnu_cxx']]],
  ['recursive_5fmutex',['recursive_mutex',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02728.html',1,'std']]],
  ['recursive_5ftimed_5fmutex',['recursive_timed_mutex',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02736.html',1,'std']]],
  ['reference',['reference',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01820.html',1,'std::bitset&lt; _Nb &gt;::reference'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08716.html',1,'std::tr2::dynamic_bitset&lt; _WordT, _Alloc &gt;::reference']]],
  ['reference_5fwrapper',['reference_wrapper',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05776.html',1,'std::reference_wrapper&lt; _Tp &gt;'],['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1reference__wrapper.html',1,'sigc::reference_wrapper&lt; class &gt;']]],
  ['refptr',['RefPtr',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1RefPtr.html',1,'Cairo::RefPtr&lt; T_CppObject &gt;'],['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1RefPtr.html',1,'Glib::RefPtr&lt; T_CppObject &gt;']]],
  ['refptr_3c_20cairo_3a_3adevice_20_3e',['RefPtr&lt; Cairo::Device &gt;',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1RefPtr.html',1,'']]],
  ['refptr_3c_20gtk_3a_3aliststore_20_3e',['RefPtr&lt; Gtk::ListStore &gt;',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1RefPtr.html',1,'Glib']]],
  ['regex',['Regex',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Regex.html',1,'Glib']]],
  ['regex_5ferror',['regex_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05912.html',1,'std']]],
  ['regex_5fiterator',['regex_iterator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05804.html',1,'std']]],
  ['regex_5ftoken_5fiterator',['regex_token_iterator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05808.html',1,'std']]],
  ['regex_5ftraits',['regex_traits',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05792.html',1,'std']]],
  ['regex_5ftraits_3c_20_5fchartype_20_3e',['regex_traits&lt; _CharType &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05792.html',1,'']]],
  ['regexerror',['RegexError',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1RegexError.html',1,'Glib']]],
  ['region',['Region',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1Region.html',1,'Cairo']]],
  ['regionselection',['RegionSelection',['../class_gtk_1_1_p_lplot_1_1_region_selection.html',1,'Gtk::PLplot']]],
  ['relation',['Relation',['http://library.gnome.org/devel/atkmm/unstable/classAtk_1_1Relation.html',1,'Atk']]],
  ['relationset',['RelationSet',['http://library.gnome.org/devel/atkmm/unstable/classAtk_1_1RelationSet.html',1,'Atk']]],
  ['remoteactiongroup',['RemoteActionGroup',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1RemoteActionGroup.html',1,'Gio']]],
  ['renderer',['Renderer',['http://library.gnome.org/devel/pangomm/unstable/classPango_1_1Renderer.html',1,'Pango']]],
  ['resize_5ferror',['resize_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10060.html',1,'__gnu_pbds']]],
  ['resize_5fpolicy',['resize_policy',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10532.html',1,'__gnu_pbds::detail']]],
  ['resize_5fpolicy_3c_20_5falloc_3a_3asize_5ftype_20_3e',['resize_policy&lt; _Alloc::size_type &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10532.html',1,'']]],
  ['resolver',['Resolver',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1Resolver.html',1,'Gio']]],
  ['resolvererror',['ResolverError',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1ResolverError.html',1,'Gio']]],
  ['resource',['Resource',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1Resource.html',1,'Gio']]],
  ['resourceerror',['ResourceError',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1ResourceError.html',1,'Gio']]],
  ['retype_5ffunctor',['retype_functor',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1retype__functor.html',1,'sigc']]],
  ['retype_5freturn_5ffunctor',['retype_return_functor',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1retype__return__functor.html',1,'sigc']]],
  ['retype_5freturn_5ffunctor_3c_20void_2c_20t_5ffunctor_20_3e',['retype_return_functor&lt; void, T_functor &gt;',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1retype__return__functor_3_01void_00_01T__functor_01_4.html',1,'sigc']]],
  ['revealer',['Revealer',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Revealer.html',1,'Gtk']]],
  ['reverse_5fiterator',['reverse_iterator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06612.html',1,'std']]],
  ['rgba',['RGBA',['http://library.gnome.org/devel/gtkmm/unstable/classGdk_1_1RGBA.html',1,'Gdk']]],
  ['rope',['rope',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08168.html',1,'__gnu_cxx']]],
  ['runtime_5ferror',['runtime_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02920.html',1,'std']]],
  ['rwlock',['RWLock',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Threads_1_1RWLock.html',1,'Glib::Threads::RWLock'],['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1RWLock.html',1,'Glib::RWLock']]]
];
