var searchData=
[
  ['data',['Data',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentManager_1_1Data.html',1,'Gtk::RecentManager']]],
  ['datainputstream',['DataInputStream',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1DataInputStream.html',1,'Gio']]],
  ['dataoutputstream',['DataOutputStream',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1DataOutputStream.html',1,'Gio']]],
  ['date',['Date',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Date.html',1,'Glib']]],
  ['datetime',['DateTime',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1DateTime.html',1,'Glib']]],
  ['dbusobjectpathstring',['DBusObjectPathString',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1DBusObjectPathString.html',1,'Glib']]],
  ['dbussignaturestring',['DBusSignatureString',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1DBusSignatureString.html',1,'Glib']]],
  ['debug_5fallocator',['debug_allocator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09284.html',1,'__gnu_cxx']]],
  ['decimal128',['decimal128',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08756.html',1,'std::decimal']]],
  ['decimal32',['decimal32',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08748.html',1,'std::decimal']]],
  ['decimal64',['decimal64',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08752.html',1,'std::decimal']]],
  ['deduce_5fresult_5ftype',['deduce_result_type',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1deduce__result__type.html',1,'sigc']]],
  ['default_5fcomb_5fhash_5ffn',['default_comb_hash_fn',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10384.html',1,'__gnu_pbds::detail']]],
  ['default_5fdelete',['default_delete',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06936.html',1,'std']]],
  ['default_5fdelete_3c_20_5ftp_5b_5d_3e',['default_delete&lt; _Tp[]&gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06940.html',1,'std']]],
  ['default_5feq_5ffn',['default_eq_fn',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10380.html',1,'__gnu_pbds::detail']]],
  ['default_5fhash_5ffn',['default_hash_fn',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10376.html',1,'__gnu_pbds::detail']]],
  ['default_5fparallel_5ftag',['default_parallel_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08636.html',1,'__gnu_parallel']]],
  ['default_5fprobe_5ffn',['default_probe_fn',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10396.html',1,'__gnu_pbds::detail']]],
  ['default_5fresize_5fpolicy',['default_resize_policy',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10388.html',1,'__gnu_pbds::detail']]],
  ['default_5ftrie_5faccess_5ftraits',['default_trie_access_traits',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10400.html',1,'__gnu_pbds::detail']]],
  ['default_5ftrie_5faccess_5ftraits_3c_20std_3a_3abasic_5fstring_3c_20char_2c_20char_5ftraits_2c_20std_3a_3aallocator_3c_20char_20_3e_20_3e_20_3e',['default_trie_access_traits&lt; std::basic_string&lt; Char, Char_Traits, std::allocator&lt; char &gt; &gt; &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10404.html',1,'__gnu_pbds::detail']]],
  ['default_5fupdate_5fpolicy',['default_update_policy',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10392.html',1,'__gnu_pbds::detail']]],
  ['defer_5flock_5ft',['defer_lock_t',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06244.html',1,'std']]],
  ['deque',['deque',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07764.html',1,'std::__debug::deque&lt; _Tp, _Allocator &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08032.html',1,'std::__profile::deque&lt; _Tp, _Allocator &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06388.html',1,'std::deque&lt; _Tp, _Alloc &gt;']]],
  ['deque_3c_20_5fstateseqt_20_3e',['deque&lt; _StateSeqT &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06388.html',1,'']]],
  ['desktopappinfo',['DesktopAppInfo',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1DesktopAppInfo.html',1,'Gio']]],
  ['device',['Device',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1Device.html',1,'Cairo::Device'],['http://library.gnome.org/devel/gtkmm/unstable/classGdk_1_1Device.html',1,'Gdk::Device']]],
  ['devicemanager',['DeviceManager',['http://library.gnome.org/devel/gtkmm/unstable/classGdk_1_1DeviceManager.html',1,'Gdk']]],
  ['dialog',['Dialog',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Dialog.html',1,'Gtk']]],
  ['dir',['Dir',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Dir.html',1,'Glib']]],
  ['direct_5fbases',['direct_bases',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08744.html',1,'std::tr2']]],
  ['direct_5fmask_5frange_5fhashing',['direct_mask_range_hashing',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10072.html',1,'__gnu_pbds']]],
  ['direct_5fmod_5frange_5fhashing',['direct_mod_range_hashing',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10076.html',1,'__gnu_pbds']]],
  ['diriterator',['DirIterator',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1DirIterator.html',1,'Glib']]],
  ['discard_5fblock_5fengine',['discard_block_engine',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05412.html',1,'std']]],
  ['discrete_5fdistribution',['discrete_distribution',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05560.html',1,'std']]],
  ['dispatcher',['Dispatcher',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Dispatcher.html',1,'Glib']]],
  ['display',['Display',['http://library.gnome.org/devel/gtkmm/unstable/classGdk_1_1Display.html',1,'Gdk']]],
  ['displaymanager',['DisplayManager',['http://library.gnome.org/devel/gtkmm/unstable/classGdk_1_1DisplayManager.html',1,'Gdk']]],
  ['divides',['divides',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06412.html',1,'std']]],
  ['divides_3c_20void_20_3e',['divides&lt; void &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06436.html',1,'std']]],
  ['document',['Document',['http://library.gnome.org/devel/atkmm/unstable/classAtk_1_1Document.html',1,'Atk']]],
  ['domain_5ferror',['domain_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02904.html',1,'std']]],
  ['dragcontext',['DragContext',['http://library.gnome.org/devel/gtkmm/unstable/classGdk_1_1DragContext.html',1,'Gdk']]],
  ['drawingarea',['DrawingArea',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1DrawingArea.html',1,'Gtk']]],
  ['drawingcontext',['DrawingContext',['http://library.gnome.org/devel/gtkmm/unstable/classGdk_1_1DrawingContext.html',1,'Gdk']]],
  ['drive',['Drive',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1Drive.html',1,'Gio']]],
  ['dumnode_5fconst_5fiterator',['dumnode_const_iterator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10580.html',1,'__gnu_pbds::detail']]],
  ['duration',['duration',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01832.html',1,'std::chrono']]],
  ['duration_5fvalues',['duration_values',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01892.html',1,'std::chrono']]],
  ['dynamic_5fbitset',['dynamic_bitset',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08712.html',1,'std::tr2']]]
];
