var searchData=
[
  ['radialgradient_16173',['RadialGradient',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1RadialGradient.html',1,'Cairo']]],
  ['radioaction_16174',['RadioAction',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RadioAction.html',1,'Gtk']]],
  ['radiobutton_16175',['RadioButton',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RadioButton.html',1,'Gtk']]],
  ['radiobuttongroup_16176',['RadioButtonGroup',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RadioButtonGroup.html',1,'Gtk']]],
  ['radiomenuitem_16177',['RadioMenuItem',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RadioMenuItem.html',1,'Gtk']]],
  ['radiotoolbutton_16178',['RadioToolButton',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RadioToolButton.html',1,'Gtk']]],
  ['rand_16179',['Rand',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Rand.html',1,'Glib']]],
  ['random_5faccess_5fiterator_5ftag_16180',['random_access_iterator_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06668.html',1,'std']]],
  ['random_5fcondition_16181',['random_condition',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09628.html',1,'__gnu_cxx']]],
  ['random_5fdevice_16182',['random_device',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05424.html',1,'std']]],
  ['range_16183',['Range',['http://library.gnome.org/devel/atkmm/unstable/classAtk_1_1Range.html',1,'Atk::Range'],['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Range.html',1,'Gtk::Range']]],
  ['range_5ferror_16184',['range_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02924.html',1,'std']]],
  ['range_5finvalidation_5fguarantee_16185',['range_invalidation_guarantee',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10124.html',1,'__gnu_pbds']]],
  ['ranged_5fhash_5ffn_16186',['ranged_hash_fn',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10668.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fhash_5ffn_3c_20key_2c_20hash_5ffn_2c_20_5falloc_2c_20comb_5fhash_5ffn_2c_20false_20_3e_16187',['ranged_hash_fn&lt; Key, Hash_Fn, _Alloc, Comb_Hash_Fn, false &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10672.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fhash_5ffn_3c_20key_2c_20hash_5ffn_2c_20_5falloc_2c_20comb_5fhash_5ffn_2c_20true_20_3e_16188',['ranged_hash_fn&lt; Key, Hash_Fn, _Alloc, Comb_Hash_Fn, true &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10676.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fhash_5ffn_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20comb_5fhash_5ffn_2c_20false_20_3e_16189',['ranged_hash_fn&lt; Key, null_type, _Alloc, Comb_Hash_Fn, false &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10680.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fhash_5ffn_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20comb_5fhash_5ffn_2c_20true_20_3e_16190',['ranged_hash_fn&lt; Key, null_type, _Alloc, Comb_Hash_Fn, true &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10684.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fprobe_5ffn_16191',['ranged_probe_fn',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10688.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fprobe_5ffn_3c_20key_2c_20hash_5ffn_2c_20_5falloc_2c_20comb_5fprobe_5ffn_2c_20probe_5ffn_2c_20false_20_3e_16192',['ranged_probe_fn&lt; Key, Hash_Fn, _Alloc, Comb_Probe_Fn, Probe_Fn, false &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10692.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fprobe_5ffn_3c_20key_2c_20hash_5ffn_2c_20_5falloc_2c_20comb_5fprobe_5ffn_2c_20probe_5ffn_2c_20true_20_3e_16193',['ranged_probe_fn&lt; Key, Hash_Fn, _Alloc, Comb_Probe_Fn, Probe_Fn, true &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10696.html',1,'__gnu_pbds::detail']]],
  ['ranged_5fprobe_5ffn_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20comb_5fprobe_5ffn_2c_20null_5ftype_2c_20false_20_3e_16194',['ranged_probe_fn&lt; Key, null_type, _Alloc, Comb_Probe_Fn, null_type, false &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10700.html',1,'__gnu_pbds::detail']]],
  ['ratio_16195',['ratio',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02828.html',1,'std']]],
  ['ratio_5fequal_16196',['ratio_equal',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02840.html',1,'std']]],
  ['ratio_5fnot_5fequal_16197',['ratio_not_equal',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02844.html',1,'std']]],
  ['raw_5fstorage_5fiterator_16198',['raw_storage_iterator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06776.html',1,'std']]],
  ['rb_5ftree_16199',['rb_tree',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08152.html',1,'__gnu_cxx']]],
  ['rb_5ftree_5fmap_16200',['rb_tree_map',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10896.html',1,'__gnu_pbds::detail']]],
  ['rb_5ftree_5fnode_5f_16201',['rb_tree_node_',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10888.html',1,'__gnu_pbds::detail']]],
  ['rb_5ftree_5ftag_16202',['rb_tree_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10164.html',1,'__gnu_pbds']]],
  ['rc_16203',['rc',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10908.html',1,'__gnu_pbds::detail']]],
  ['rc_3c_20typename_20binomial_5fheap_5fbase_3c_20value_5ftype_2c_20cmp_5ffn_2c_20_5falloc_20_3e_3a_3anode_2c_20_5falloc_20_3e_16204',['rc&lt; typename binomial_heap_base&lt; Value_Type, Cmp_Fn, _Alloc &gt;::node, _Alloc &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10908.html',1,'']]],
  ['rc_5fbinomial_5fheap_16205',['rc_binomial_heap',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10912.html',1,'__gnu_pbds::detail']]],
  ['rc_5fbinomial_5fheap_5ftag_16206',['rc_binomial_heap_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10200.html',1,'__gnu_pbds']]],
  ['readerlock_16207',['ReaderLock',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1RWLock_1_1ReaderLock.html',1,'Glib::RWLock::ReaderLock'],['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Threads_1_1RWLock_1_1ReaderLock.html',1,'Glib::Threads::RWLock::ReaderLock']]],
  ['recentaction_16208',['RecentAction',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentAction.html',1,'Gtk']]],
  ['recentchooser_16209',['RecentChooser',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentChooser.html',1,'Gtk']]],
  ['recentchooserdialog_16210',['RecentChooserDialog',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentChooserDialog.html',1,'Gtk']]],
  ['recentchoosererror_16211',['RecentChooserError',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentChooserError.html',1,'Gtk']]],
  ['recentchoosermenu_16212',['RecentChooserMenu',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentChooserMenu.html',1,'Gtk']]],
  ['recentchooserwidget_16213',['RecentChooserWidget',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentChooserWidget.html',1,'Gtk']]],
  ['recentfilter_16214',['RecentFilter',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentFilter.html',1,'Gtk']]],
  ['recentinfo_16215',['RecentInfo',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentInfo.html',1,'Gtk']]],
  ['recentmanager_16216',['RecentManager',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentManager.html',1,'Gtk']]],
  ['recentmanagererror_16217',['RecentManagerError',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1RecentManagerError.html',1,'Gtk']]],
  ['recmutex_16218',['RecMutex',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Threads_1_1RecMutex.html',1,'Glib::Threads::RecMutex'],['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1RecMutex.html',1,'Glib::RecMutex']]],
  ['rectangle_16219',['Rectangle',['http://library.gnome.org/devel/gtkmm/unstable/classGdk_1_1Rectangle.html',1,'Gdk::Rectangle'],['http://library.gnome.org/devel/pangomm/unstable/classPango_1_1Rectangle.html',1,'Pango::Rectangle']]],
  ['recursive_5finit_5ferror_16220',['recursive_init_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01648.html',1,'__gnu_cxx']]],
  ['recursive_5fmutex_16221',['recursive_mutex',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02728.html',1,'std']]],
  ['recursive_5ftimed_5fmutex_16222',['recursive_timed_mutex',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02736.html',1,'std']]],
  ['reference_16223',['reference',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08716.html',1,'std::tr2::dynamic_bitset&lt; _WordT, _Alloc &gt;::reference'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01820.html',1,'std::bitset&lt; _Nb &gt;::reference']]],
  ['reference_5fwrapper_16224',['reference_wrapper',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05776.html',1,'std::reference_wrapper&lt; _Tp &gt;'],['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1reference__wrapper.html',1,'sigc::reference_wrapper&lt; class &gt;']]],
  ['refptr_16225',['RefPtr',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1RefPtr.html',1,'Cairo::RefPtr&lt; T_CppObject &gt;'],['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1RefPtr.html',1,'Glib::RefPtr&lt; T_CppObject &gt;']]],
  ['refptr_3c_20cairo_3a_3adevice_20_3e_16226',['RefPtr&lt; Cairo::Device &gt;',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1RefPtr.html',1,'']]],
  ['refptr_3c_20gtk_3a_3aliststore_20_3e_16227',['RefPtr&lt; Gtk::ListStore &gt;',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1RefPtr.html',1,'Glib']]],
  ['regex_16228',['Regex',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Regex.html',1,'Glib']]],
  ['regex_5ferror_16229',['regex_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05912.html',1,'std']]],
  ['regex_5fiterator_16230',['regex_iterator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05804.html',1,'std']]],
  ['regex_5ftoken_5fiterator_16231',['regex_token_iterator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05808.html',1,'std']]],
  ['regex_5ftraits_16232',['regex_traits',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05792.html',1,'std']]],
  ['regex_5ftraits_3c_20_5fchartype_20_3e_16233',['regex_traits&lt; _CharType &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05792.html',1,'']]],
  ['regexerror_16234',['RegexError',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1RegexError.html',1,'Glib']]],
  ['region_16235',['Region',['http://www.cairographics.org/documentation/cairomm/reference/classCairo_1_1Region.html',1,'Cairo']]],
  ['regionselection_16236',['RegionSelection',['../class_gtk_1_1_p_lplot_1_1_region_selection.html',1,'Gtk::PLplot']]],
  ['relation_16237',['Relation',['http://library.gnome.org/devel/atkmm/unstable/classAtk_1_1Relation.html',1,'Atk']]],
  ['relationset_16238',['RelationSet',['http://library.gnome.org/devel/atkmm/unstable/classAtk_1_1RelationSet.html',1,'Atk']]],
  ['remoteactiongroup_16239',['RemoteActionGroup',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1RemoteActionGroup.html',1,'Gio']]],
  ['renderer_16240',['Renderer',['http://library.gnome.org/devel/pangomm/unstable/classPango_1_1Renderer.html',1,'Pango']]],
  ['resize_5ferror_16241',['resize_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10060.html',1,'__gnu_pbds']]],
  ['resize_5fpolicy_16242',['resize_policy',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10532.html',1,'__gnu_pbds::detail']]],
  ['resize_5fpolicy_3c_20_5falloc_3a_3asize_5ftype_20_3e_16243',['resize_policy&lt; _Alloc::size_type &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10532.html',1,'']]],
  ['resolver_16244',['Resolver',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1Resolver.html',1,'Gio']]],
  ['resolvererror_16245',['ResolverError',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1ResolverError.html',1,'Gio']]],
  ['resource_16246',['Resource',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1Resource.html',1,'Gio']]],
  ['resourceerror_16247',['ResourceError',['http://library.gnome.org/devel/glibmm/unstable/classGio_1_1ResourceError.html',1,'Gio']]],
  ['retype_5ffunctor_16248',['retype_functor',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1retype__functor.html',1,'sigc']]],
  ['retype_5freturn_5ffunctor_16249',['retype_return_functor',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1retype__return__functor.html',1,'sigc']]],
  ['retype_5freturn_5ffunctor_3c_20void_2c_20t_5ffunctor_20_3e_16250',['retype_return_functor&lt; void, T_functor &gt;',['http://library.gnome.org/devel/libsigc++/unstable/structsigc_1_1retype__return__functor_3_01void_00_01T__functor_01_4.html',1,'sigc']]],
  ['revealer_16251',['Revealer',['http://library.gnome.org/devel/gtkmm/unstable/classGtk_1_1Revealer.html',1,'Gtk']]],
  ['reverse_5fiterator_16252',['reverse_iterator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06612.html',1,'std']]],
  ['rgba_16253',['RGBA',['http://library.gnome.org/devel/gtkmm/unstable/classGdk_1_1RGBA.html',1,'Gdk']]],
  ['rope_16254',['rope',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08168.html',1,'__gnu_cxx']]],
  ['runtime_5ferror_16255',['runtime_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02920.html',1,'std']]],
  ['rwlock_16256',['RWLock',['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1RWLock.html',1,'Glib::RWLock'],['http://library.gnome.org/devel/glibmm/unstable/classGlib_1_1Threads_1_1RWLock.html',1,'Glib::Threads::RWLock']]]
];
