var searchData=
[
  ['nested_5fexception_2eh',['nested_exception.h',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00419.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01326.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01326.html',1,'(Global Namespace)']]],
  ['new',['new',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00032.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01327.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01327.html',1,'(Global Namespace)']]],
  ['new_5fallocator_2eh',['new_allocator.h',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01058.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01328.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01328.html',1,'(Global Namespace)']]],
  ['node_5fhandle_2eh',['node_handle.h',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00422.html',1,'']]],
  ['null_5fnode_5fmetadata_2ehpp',['null_node_metadata.hpp',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01235.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01336.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01336.html',1,'(Global Namespace)']]],
  ['numeric',['numeric',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00113.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01337.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01337.html',1,'(Global Namespace)']]],
  ['numeric_5ftraits_2eh',['numeric_traits.h',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01061.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01340.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01340.html',1,'(Global Namespace)']]],
  ['numericfwd_2eh',['numericfwd.h',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00914.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01341.html',1,'(Global Namespace)'],['http://www.cairographics.org/documentation/cairomm/reference/a01341.html',1,'(Global Namespace)']]]
];
